### ISSUE TITLE
Format of Price Column Unspecified

### ISSUE THREAD

**Issue by J-M-White** [v715/VenmoCalculator#2]
Based on my own testing, it seems like the price column needs to be formatted with a '$' (or other single character) at the beginning; however, this is not mentioned in the documentation anywhere.

**Comment by eigenvivek** [comment]
ah yes right you are, thank you for the comment

I have assumed the first character is a `$`:
https://github.com/eigenvivek/VenmoCalculator/blob/3cb67bfba0cf84a93f0616d3813a5fdecbcd92d3/calculator.py#L9

the README will be updated to document this
